"""add proposed_updates table

Revision ID: 7bc42a97943c
Revises: c43ea2d3a99c
Create Date: 2026-10-10 02:05:02.349021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc42a97943c'
down_revision: Union[str, None] = 'c43ea2d3a99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('current_value', sa.String(), nullable=False),
    sa.Column('proposed_value', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('proposed_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('review_note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('sector_vulnerability', 'transition_sensitivity', 'scenario_archetype', 'other')", name='ck_proposal_kind'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_proposal_status'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposed_updates')
    # ### end Alembic commands ###
