"""initial schema

Revision ID: c43ea2d3a99c
Revises: 
Create Date: 2026-10-09 22:15:20.625629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43ea2d3a99c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('evidence_class', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.CheckConstraint('weight >= 1 AND weight <= 3', name='ck_edge_weight_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependency_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependency_edges_edge_type'), ['edge_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependency_edges_from_id'), ['from_id'], unique=False)
        batch_op.create_index('ix_dependency_edges_from_to', ['from_id', 'to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependency_edges_to_id'), ['to_id'], unique=False)

    op.create_table('evidence_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('evidence_class', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("evidence_class IN ('sourced', 'modelled', 'assumption', 'synthetic')", name='ck_evidence_class'),
    sa.CheckConstraint("subject_type IN ('company', 'hazard', 'portfolio', 'scenario', 'institution')", name='ck_evidence_subject_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_records_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_evidence_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('hazard_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('evidence_class', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hazard_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hazard_events_region'), ['region'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ceded_reinsurance_share_pct', sa.Float(), nullable=True),
    sa.Column('reinsurer_name', sa.String(), nullable=True),
    sa.Column('govt_subsidy_pct', sa.Float(), nullable=True),
    sa.CheckConstraint("kind IN ('bank', 'govt', 'insurer')", name='ck_institution_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_institutions_kind_region', ['kind', 'region'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_region'), ['region'], unique=False)

    op.create_table('news_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_query'), ['query'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('org_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osm_ways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=False),
    sa.Column('bbox_key', sa.String(), nullable=False),
    sa.Column('highway', sa.String(), nullable=True),
    sa.Column('bridge', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry_json', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osm_ways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_ways_bbox_key'), ['bbox_key'], unique=False)

    op.create_table('scenario_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('hazard', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('substitutability', sa.String(), nullable=False),
    sa.Column('interventions', sa.String(), nullable=False),
    sa.Column('baseline_el_cr', sa.Float(), nullable=False),
    sa.Column('stressed_el_cr', sa.Float(), nullable=False),
    sa.Column('mitigated_el_cr', sa.Float(), nullable=False),
    sa.Column('company_count', sa.Integer(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('sourced_weight_pct', sa.Float(), nullable=False),
    sa.Column('modelled_weight_pct', sa.Float(), nullable=False),
    sa.Column('assumption_weight_pct', sa.Float(), nullable=False),
    sa.Column('synthetic_weight_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_runs_region'), ['region'], unique=False)

    op.create_table('weather_anomalies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_std', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('isolation_forest_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('method_agreement', sa.Boolean(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_weather_anomaly_location_date', ['lat', 'lng', 'date'], unique=False)

    op.create_table('weather_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('temp_c_avg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index('ix_weather_obs_location_date', ['lat', 'lng', 'date'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('ead_cr', sa.Float(), nullable=False),
    sa.Column('baseline_pd', sa.Float(), nullable=False),
    sa.Column('baseline_lgd', sa.Float(), nullable=False),
    sa.Column('annual_revenue_cr', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('insurer_id', sa.String(), nullable=True),
    sa.Column('sum_insured_cr', sa.Float(), nullable=True),
    sa.Column('premium_rate_bps', sa.Float(), nullable=True),
    sa.Column('deductible_pct', sa.Float(), nullable=True),
    sa.CheckConstraint('baseline_lgd >= 0 AND baseline_lgd <= 1', name='ck_company_lgd_range'),
    sa.CheckConstraint('baseline_pd >= 0 AND baseline_pd <= 1', name='ck_company_pd_range'),
    sa.CheckConstraint('ead_cr >= 0', name='ck_company_ead_nonneg'),
    sa.ForeignKeyConstraint(['insurer_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_insurer_id'), ['insurer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_region'), ['region'], unique=False)
        batch_op.create_index('ix_companies_region_sector', ['region', 'sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_sector'), ['sector'], unique=False)

    op.create_table('news_entity_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_label', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("entity_type IN ('company', 'region')", name='ck_entity_link_type'),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_entity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_entity_links_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_news_entity_links_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mandate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geo_confidence', sa.String(), nullable=False),
    sa.Column('geocode_source', sa.String(), nullable=False),
    sa.Column('geocode_raw_importance', sa.Float(), nullable=True),
    sa.CheckConstraint("geo_confidence IN ('exact', 'approximate', 'centroid')", name='ck_asset_geo_confidence'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_kind'), ['kind'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('quantity_or_share', sa.Float(), nullable=False),
    sa.Column('cost_basis_cr', sa.Float(), nullable=False),
    sa.Column('market_value_cr', sa.Float(), nullable=False),
    sa.Column('valuation_date', sa.String(), nullable=False),
    sa.Column('liquidity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_kind'))

    op.drop_table('assets')
    op.drop_table('portfolios')
    with op.batch_alter_table('news_entity_links', schema=None) as batch_op:
        batch_op.drop_index('ix_news_entity_links_entity')
        batch_op.drop_index(batch_op.f('ix_news_entity_links_article_id'))

    op.drop_table('news_entity_links')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_sector'))
        batch_op.drop_index('ix_companies_region_sector')
        batch_op.drop_index(batch_op.f('ix_companies_region'))
        batch_op.drop_index(batch_op.f('ix_companies_insurer_id'))

    op.drop_table('companies')
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_obs_location_date')

    op.drop_table('weather_observations')
    with op.batch_alter_table('weather_anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_anomaly_location_date')

    op.drop_table('weather_anomalies')
    with op.batch_alter_table('scenario_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_runs_region'))
        batch_op.drop_index(batch_op.f('ix_scenario_runs_created_at'))

    op.drop_table('scenario_runs')
    with op.batch_alter_table('osm_ways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osm_ways_bbox_key'))

    op.drop_table('osm_ways')
    op.drop_table('organizations')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_query'))

    op.drop_table('news_articles')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_region'))
        batch_op.drop_index('ix_institutions_kind_region')
        batch_op.drop_index(batch_op.f('ix_institutions_kind'))

    op.drop_table('institutions')
    with op.batch_alter_table('hazard_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazard_events_region'))

    op.drop_table('hazard_events')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_subject')
        batch_op.drop_index(batch_op.f('ix_evidence_records_subject_id'))

    op.drop_table('evidence_records')
    with op.batch_alter_table('dependency_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependency_edges_to_id'))
        batch_op.drop_index('ix_dependency_edges_from_to')
        batch_op.drop_index(batch_op.f('ix_dependency_edges_from_id'))
        batch_op.drop_index(batch_op.f('ix_dependency_edges_edge_type'))

    op.drop_table('dependency_edges')
    # ### end Alembic commands ###
